In [144]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.axes as ax
from matplotlib.animation import FuncAnimation

data = pd.read_csv('/content/loan_data.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

In [145]:
missing_valus = data.isna().sum().sort_values(ascending=False)
missing_valus

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [146]:
data.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [147]:
cinsiyet_mapping = {'female': 0.0, 'male': 1.0}
data['person_gender'] = data['person_gender'].map(cinsiyet_mapping)

In [148]:
education_mapping = {'Bachelor': 0.0, 'Associate': 1.0, 'High School': 3.0, 'Master': 4.0, 'Doctorate': 5.0}
data['person_education'] = data['person_education'].map(education_mapping)

In [149]:
ownership_mapping = {'RENT': 0.0,'OWN': 1.0, 'MORTGAGE': 2.0,'OTHER':3.0 }
data['person_home_ownership'] = data['person_home_ownership'].map(ownership_mapping)

In [150]:
loan_intent_mapping = {'PERSONAL': 0.0, 'EDUCATION': 1.0, 'MEDICAL': 2.0, 'VENTURE': 3.0, 'HOMEIMPROVEMENT': 4.0, 'DEBTCONSOLIDATION': 5.0}
data['loan_intent'] = data['loan_intent'].map(loan_intent_mapping)

In [151]:
previous_mapping = {'No' : 0.0, 'Yes' : 1.0}
data['previous_loan_defaults_on_file'] = data['previous_loan_defaults_on_file'].map(previous_mapping)

In [152]:
data.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,0.0,4.0,71948.0,0,0.0,35000.0,0.0,16.02,0.49,3.0,561,0.0,1
1,21.0,0.0,3.0,12282.0,0,1.0,1000.0,1.0,11.14,0.08,2.0,504,1.0,0
2,25.0,0.0,3.0,12438.0,3,2.0,5500.0,2.0,12.87,0.44,3.0,635,0.0,1
3,23.0,0.0,0.0,79753.0,0,0.0,35000.0,2.0,15.23,0.44,2.0,675,0.0,1
4,24.0,1.0,4.0,66135.0,1,0.0,35000.0,2.0,14.27,0.53,4.0,586,0.0,1

In [153]:
missing_valus = data.isna().sum().sort_values(ascending=False)
missing_valus

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [154]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [155]:
X = data.iloc[:, :-1].values  # 14 sütundan ilk 13'ü
y = data.iloc[:, -1].values   # son sütun

In [156]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [157]:
model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [158]:
opt = Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=10, verbose=1)

loss, accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

Epoch 1/10
3600/3600 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - accuracy: 0.8779 - loss: 0.2594
Epoch 2/10
3600/3600 ━━━━━━━━━━━━━━━━━━━━ 15s 2ms/step - accuracy: 0.9058 - loss: 0.2045
Epoch 3/10
3600/3600 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - accuracy: 0.9107 - loss: 0.1985
Epoch 4/10
3600/3600 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9148 - loss: 0.1909
Epoch 5/10
3600/3600 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.9122 - loss: 0.1941
Epoch 6/10
3600/3600 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9175 - loss: 0.1885
Epoch 7/10
3600/3600 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - accuracy: 0.9164 - loss: 0.1877
Epoch 8/10
3600/3600 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.9170 - loss: 0.1878
Epoch 9/10
3600/3600 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.9150 - loss: 0.1877
Epoch 10/10
3600/3600 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - accuracy: 0.9182 - loss: 0.1830
282/282 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9084 - loss: 0.1978
Test Loss: 0.19689325988292694
Test Accuracy: 0.9092222452163696